### PR TITLE
Reduce amount of heap allocations in palindromes benchmark

### PR DESCRIPTION
**Pull request by Robbepop**
Context: https://www.reddit.com/r/rust/comments/le38yb/typescript_function_running_faster_than_wasm/gm9txzs/?utm_source=reddit&utm_medium=web2x&context=3

### CODE REVIEW

**Comment by Robbepop** [comment]
You stated in a reply that you "sent a review" for my PR but it does not show up here. Maybe you forgot to actually submit your review? @lescuer97 

I'd be interested in how this version performs compared to Typescript even though I can see that you already took over the version proposed by the other user.

**Comment by lescuer97** [comment]
I don't know why is not showing  the Selected code: 
Its in line +16 to +19 of your pr, I'm not really getting what you are doing with that iter and where does the reverse come from in the closure?

**Comment by Robbepop** [comment]
I use https://doc.rust-lang.org/core/iter/trait.Iterator.html#method.zip in order to zip two iterators together.
So I can iterate over 2 iterators at the same time.
I am using the `chars()` iterator to iterate in a forward fashion and I am using `chars().rev()` (https://doc.rust-lang.org/core/iter/struct.Rev.html) to iterate backwards at the same time.
Then I check using https://doc.rust-lang.org/core/iter/trait.Iterator.html#method.all if all yielded iterator elements evaluate to `true` for my closure that simply compares the yielded iterator elements for equality.

So all this does is iterate through the same characters forwards and backwards and compare each pair for equality and if all those pairs are equal it must be a palindrome.

I think this solution is very clean and should also be very efficient.

**Comment by lescuer97** [comment]
oooohh , let me see if i got this right. because Zip returns both solved iterator as some kind of tupple with both the chars and the chars.rev() inside it, then all grabs that outcome and checks that both parts of this "tuple" are equal and if it returns true than you get the number inside the final array

**Comment by lescuer97** [comment]
Thank you for the Advice!

**Comment by Robbepop** [comment]
Can you tell how fast this version is compared to the TypeScript code on your machine/benchmark?

**Comment by lescuer97** [comment]
Yes, this are the results with an input of 99999999:      
 WASM: 10050, 10335, 10297
 TS: 19291, 19719, 20599

so Thank you! because the improvements are huge

**Pull request merged**
